### PR TITLE
Responses for subscriptions and unsubscriptions

### PR DESCRIPTION
**Pull request by jkpl**
Related to issue #73

### CODE REVIEW

**Comment by jkpl** [comment]
WIP

**Comment by simonsouter** [comment]
Don't see the value in this.  We can't really convey anything meaningful in the subscription response.  If a subscription does fail for whatever reason, we should propagate an error via supervision.

**Comment by psilos** [comment]
@simonsouter Thanks for the feedback Simon. The only added value from my perspective is the confirmation that the Subscription has been successfully completed, as per my comment at https://github.com/cakesolutions/scala-kafka-client/issues/73#issuecomment-261293268

This gives us the guarantee that when the actor has been created and started the subscription was successful. At the moment we only instruct / command a Subscription but there is no Event / Ack that it has actually happened. Plus we don't know how long it can take for this to happen.

**Comment by jkpl** [comment]
The problem is that we're not actually sure if we can give you a guarantee that the subscription is done correctly. With the internal client we use (the Java client), we can enqueue a subscription, but there's not a reliable way to get feedback for when it has gone through to Kafka. So far in this PR, we can only give feedback that the subscription request was received by our client that wraps the Java client.

**Pull request closed without merging**
